### PR TITLE
WIP: rotation looks nice

### PR DESCRIPTION
**Pull request by karu2003**
rotation looks nice. On Desktop. :) and RPi.

### CODE REVIEW

**Comment by Consti10** [comment]
Only saw this just now. Are you saying that the "rotate OSD by 90°" works / is usable on rpi / linux this way ?

**Comment by karu2003** [comment]
> Only saw this just now. Are you saying that the "rotate OSD by 90°" works / is usable on rpi / linux this way ?

looks good. I just saw that such menus a lot of. It need to try to add to the parents.

popup.contentItem {
                        transform: [ Rotation { angle: settings.general_screen_rotation } ]
                        transformOrigin: Item.TopLeft
                    }
                    popup.background {
                        transform: [ Rotation { angle: settings.general_screen_rotation } ]
                        transformOrigin: Item.TopLeft
                    }

:)

**Comment by karu2003** [comment]
> Only saw this just now. Are you saying that the "rotate OSD by 90°" works / is usable on rpi / linux this way ?

it can rotate everything content in one line.

**Comment by karu2003** [comment]
> Only saw this just now. Are you saying that the "rotate OSD by 90°" works / is usable on rpi / linux this way ?

why are they not being tested?  I build on RPi with no errors.

**Comment by Consti10** [comment]
They fail when they are trying to upload.
Were you able to confirm that disabling auto scaling dpi doesn't break things on platforms / screens not your case ?
I'l merge it anyways now, not many changes, so let's just get it into the main branch.

**Comment by karu2003** [comment]
with DPI it need to add a variable at startup.  or in QOpenHD  I checked on my monitor RPi and desktop.  others may need other DPI

**Comment by Consti10** [comment]
had to revert the part where you set QT_FONT_DPI.
However, I've removed and tested the artificial limitation of not being able to put in a scale <1 - works now, but you need to restart QOpenHD every time you change the scale there.

**Comment by Consti10** [comment]
> with DPI it need to add a variable at startup. or in QOpenHD I checked on my monitor RPi and desktop. others may need other DPI

Aaah, I did not understand that.
In this case, it should probably be a setting the user can change from the UI, right ?

**Pull request merged**
